### ISSUE TITLE
Assignment 1 Feedback

### ISSUE THREAD

**Issue by venpopov** [nicolas-brandao/nicolas-brandao-ICMB-HS24#1]
Everything look good. There is just one minor thing to do - add your website link to the about section as in the screenshot below. Currently your about section is empty and to find the link I had to search for it in a different place. You can respond to this issue when you are done.

![image](https://github.com/user-attachments/assets/61d759e8-047a-4076-8d5e-a5762ba3b622)

**Comment by nicolas-brandao** [comment]
[like]  Nicolas Brandao reacted to your message:
________________________________
From: Ven Popov ***@***.***>
Sent: Tuesday, October 1, 2024 4:00:19 PM
To: brandao-nicolas/nicolas-brandao-ICMB-HS24 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [brandao-nicolas/nicolas-brandao-ICMB-HS24] Assignment 1 Feedback (Issue #1)


Everything look good. There is just one minor thing to do - add your website link to the about section as in the screenshot below. Currently your about section is empty and to find the link I had to search for it in a different place.

image.png (view on web)<https://github.com/user-attachments/assets/61d759e8-047a-4076-8d5e-a5762ba3b622>

**Comment by nicolas-brandao** [comment]
[0]     Nicolas Brandao reacted to your message:
________________________________
From: Ven Popov ***@***.***>
Sent: Tuesday, October 1, 2024 4:00:19 PM
To: brandao-nicolas/nicolas-brandao-ICMB-HS24 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [brandao-nicolas/nicolas-brandao-ICMB-HS24] Assignment 1 Feedback (Issue #1)


Everything look good. There is just one minor thing to do - add your website link to the about section as in the screenshot below. Currently your about section is empty and to find the link I had to search for it in a different place.

image.png (view on web)<https://github.com/user-attachments/assets/61d759e8-047a-4076-8d5e-a5762ba3b622>
